### ISSUE TITLE
AttributeError: 'list' object has no attribute 'to_bytes'

### ISSUE THREAD

**Issue by doudz** [zigpy/zigpy-zigate#136]
@puddly  : There's an error in the last update

Thank for all you've done but please don't deploy a new release without test it

```
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/components/zha/__init__.py", line 112, in async_setup_entry
    await zha_gateway.async_initialize()
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/components/zha/core/gateway.py", line 185, in async_initialize
    raise exc
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/components/zha/core/gateway.py", line 172, in async_initialize
    self.application_controller = await app_controller_cls.new(
  File "/srv/homeassistant/lib/python3.10/site-packages/zigpy/application.py", line 144, in new
    await app.startup(auto_form=auto_form)
  File "/srv/homeassistant/lib/python3.10/site-packages/zigpy/application.py", line 124, in startup
    await self.connect()
  File "/srv/homeassistant/lib/python3.10/site-packages/zigpy_zigate/zigbee/application.py", line 47, in connect
    major, minor = version.to_bytes(2, "big")
AttributeError: 'list' object has no attribute 'to_bytes'
```

**Comment by puddly** [comment]
I'm doing what I can. Zigpy-zigate is the only radio library with 60% unit test coverage, little of which covers any useful part of `application.py`.
