### ISSUE TITLE
PiZigate connecting to ZHA on a docker home assistant result to "Failed to connect"

### ISSUE THREAD

**Issue by PapyElGringo** [zigpy/zigpy-zigate#140]
Hello, I'm trying to connect my PiZigate v1 to a new homeassistant installation and I failed to link it to the ZHA integration. After enabling the debug this is the logs I get.
```
2022-10-12 00:08:20.017 DEBUG (MainThread) [zigpy_zigate.uart] PiZiGate detected
2022-10-12 00:08:20.021 INFO (SyncWorker_4) [zigpy_zigate.common] Put PiZiGate in running mode
2022-10-12 00:08:20.020 DEBUG (MainThread) [zigpy_zigate.api] Unsuccessful radio probe of '/dev/serial0' port
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/serial/serialposix.py", line 322, in open
self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: '/dev/serial0'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/zigpy_zigate/api.py", line 510, in probe
await asyncio.wait_for(api._probe(), timeout=PROBE_TIMEOUT)
File "/usr/local/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
return fut.result()
File "/usr/local/lib/python3.10/site-packages/zigpy_zigate/api.py", line 535, in _probe
await self.connect()
File "/usr/local/lib/python3.10/site-packages/zigpy_zigate/api.py", line 235, in connect
self._uart = await zigpy_zigate.uart.connect(self._config, self)
File "/usr/local/lib/python3.10/site-packages/zigpy_zigate/uart.py", line 154, in connect
_, protocol = await zigpy.serial.create_serial_connection(
File "/usr/local/lib/python3.10/site-packages/zigpy/serial.py", line 37, in create_serial_connection
transport, protocol = await pyserial_asyncio.create_serial_connection(
File "/usr/local/lib/python3.10/site-packages/serial_asyncio/__init__.py", line 448, in create_serial_connection
serial_instance = serial.serial_for_url(*args, **kwargs)
File "/usr/local/lib/python3.10/site-packages/serial/__init__.py", line 90, in serial_for_url
instance.open()
File "/usr/local/lib/python3.10/site-packages/serial/serialposix.py", line 325, in open
raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port /dev/serial0: [Errno 2] No such file or directory: '/dev/serial0'
```
Any idea?

**Comment by PapyElGringo** [comment]
using ` ls -l /dev/ser*` gave me `/dev/serial0 -> ttyS0` and when I connected to `/dev/ttyS0` it's worked
